export { executeActions } from './actions.js'
export type { ExecuteResult, PlannedAction } from './actions.js'
export { analyzeInbox } from './analyze.js'
export type { AnalyzeReport, DomainTally } from './analyze.js'
export { readProvider, scanOptions, withMeta } from './context.js'
export type { PipelineContext, RunMeta } from './context.js'
export { fileInbox } from './file.js'
export type { FileOptions, FileReport } from './file.js'
export { scoreInboxNeedsAction } from './needs-action.js'
export type { NeedsActionCandidate, NeedsActionOptions, NeedsActionReport } from './needs-action.js'
export { bumpSender, coveragePercent, planClassification, topSenderTally } from './plan.js'
export type { PlanReport, SenderTally } from './plan.js'
export { sweepNewsletters } from './sweep.js'
export type { SweepOptions, SweepReport, SweptSender } from './sweep.js'
export { verifyRun } from './verify.js'
export type { LabelExpectation, VerifyCheck, VerifyExpectations, VerifyReport } from './verify.js'
