/**
 * Generic domain knowledge pack: globally recognizable root domains mapped to
 * generic category names. Deliberately opinion-free — nothing regional-only or
 * niche lives here. When a domain is not in this catalog the suggest engine
 * surfaces it as UNKNOWN so the user decides; the catalog never guesses.
 */

export interface SuggestedCategory {
  name: string
  label: string
  description: string
}

/** The generic categories the catalog files domains into. */
export const SUGGESTED_CATEGORIES: readonly SuggestedCategory[] = [
  { name: 'Finance', label: 'Finance', description: 'Banks, payments, fintech and crypto' },
  {
    name: 'Shopping',
    label: 'Shopping',
    description: 'Marketplaces, retail and parcel delivery',
  },
  { name: 'Travel', label: 'Travel', description: 'Flights, stays, rides and bookings' },
  {
    name: 'Development',
    label: 'Development',
    description: 'Code hosting, developer tools and infrastructure',
  },
  { name: 'Social', label: 'Social', description: 'Social networks and messaging platforms' },
  { name: 'Jobs', label: 'Jobs', description: 'Job boards, recruiting and applications' },
  { name: 'News', label: 'News', description: 'Newspapers, magazines and newsletters' },
  {
    name: 'Entertainment',
    label: 'Entertainment',
    description: 'Streaming, music, gaming and events',
  },
  { name: 'Health', label: 'Health', description: 'Fitness, wellness and health tracking' },
  { name: 'Telecom', label: 'Telecom', description: 'Mobile carriers and internet providers' },
  { name: 'Cloud', label: 'Cloud', description: 'Productivity SaaS and cloud storage' },
  {
    name: 'Accounts',
    label: 'Accounts',
    description: 'Account, identity and security notifications',
  },
]

/**
 * Curated domains grouped by category, exported for display/tests; the flat
 * lookup view is DOMAIN_CATALOG below. Rule of thumb: global household names
 * only — when in doubt, leave it out and let the engine ask the user.
 */
export const CATALOG_DOMAINS_BY_CATEGORY: Readonly<Record<string, readonly string[]>> = {
  Finance: [
    'paypal.com',
    'stripe.com',
    'wise.com',
    'revolut.com',
    'n26.com',
    'monzo.com',
    'klarna.com',
    'coinbase.com',
    'binance.com',
    'kraken.com',
    'venmo.com',
    'cash.app',
    'robinhood.com',
    'americanexpress.com',
    'visa.com',
    'mastercard.com',
    'hsbc.com',
    'westernunion.com',
  ],
  Shopping: [
    'amazon.com',
    'ebay.com',
    'etsy.com',
    'aliexpress.com',
    'alibaba.com',
    'walmart.com',
    'ikea.com',
    'nike.com',
    'adidas.com',
    'hm.com',
    'shein.com',
    'temu.com',
    'wish.com',
    'rakuten.com',
    'shopify.com',
    'groupon.com',
    'dhl.com',
    'ups.com',
    'fedex.com',
  ],
  Travel: [
    'booking.com',
    'airbnb.com',
    'uber.com',
    'lyft.com',
    'expedia.com',
    'tripadvisor.com',
    'trip.com',
    'skyscanner.net',
    'kayak.com',
    'hotels.com',
    'agoda.com',
    'marriott.com',
    'hilton.com',
    'hertz.com',
    'lufthansa.com',
    'delta.com',
    'united.com',
    'emirates.com',
    'britishairways.com',
    'airfrance.com',
    'klm.com',
    'ryanair.com',
  ],
  Development: [
    'github.com',
    'gitlab.com',
    'bitbucket.org',
    'npmjs.com',
    'vercel.com',
    'netlify.com',
    'cloudflare.com',
    'amazonaws.com',
    'digitalocean.com',
    'heroku.com',
    'atlassian.com',
    'jetbrains.com',
    'docker.com',
    'hashicorp.com',
    'mongodb.com',
    'stackoverflow.com',
    'sentry.io',
    'datadoghq.com',
    'pagerduty.com',
    'postman.com',
    'figma.com',
    'supabase.com',
    'huggingface.co',
    'openai.com',
    'anthropic.com',
    'godaddy.com',
    'namecheap.com',
  ],
  Social: [
    'facebook.com',
    'instagram.com',
    'twitter.com',
    'x.com',
    'tiktok.com',
    'reddit.com',
    'discord.com',
    'snapchat.com',
    'pinterest.com',
    'whatsapp.com',
    'telegram.org',
    'signal.org',
    'meetup.com',
    'tumblr.com',
    'quora.com',
  ],
  Jobs: [
    'linkedin.com',
    'indeed.com',
    'glassdoor.com',
    'greenhouse.io',
    'lever.co',
    'workday.com',
    'myworkday.com',
    'monster.com',
    'ziprecruiter.com',
    'smartrecruiters.com',
    'wellfound.com',
  ],
  News: [
    'nytimes.com',
    'theguardian.com',
    'washingtonpost.com',
    'wsj.com',
    'bbc.com',
    'bbc.co.uk',
    'cnn.com',
    'reuters.com',
    'bloomberg.com',
    'economist.com',
    'ft.com',
    'substack.com',
    'medium.com',
    'wired.com',
  ],
  Entertainment: [
    'netflix.com',
    'spotify.com',
    'youtube.com',
    'steampowered.com',
    'twitch.tv',
    'epicgames.com',
    'disney.com',
    'disneyplus.com',
    'playstation.com',
    'xbox.com',
    'nintendo.com',
    'ea.com',
    'ubisoft.com',
    'roblox.com',
    'soundcloud.com',
    'audible.com',
    'imdb.com',
    'ticketmaster.com',
    'eventbrite.com',
    'crunchyroll.com',
  ],
  Health: [
    'fitbit.com',
    'strava.com',
    'myfitnesspal.com',
    'garmin.com',
    'headspace.com',
    'calm.com',
    'whoop.com',
    'ouraring.com',
    'peloton.com',
  ],
  Telecom: [
    'vodafone.com',
    't-mobile.com',
    'verizon.com',
    'att.com',
    'orange.com',
    'o2.com',
    'telefonica.com',
  ],
  Cloud: [
    'dropbox.com',
    'box.com',
    'zoom.us',
    'slack.com',
    'notion.so',
    'evernote.com',
    'asana.com',
    'monday.com',
    'canva.com',
    'adobe.com',
    'salesforce.com',
    'hubspot.com',
    'mailchimp.com',
    'zendesk.com',
    'docusign.com',
    'grammarly.com',
    'calendly.com',
    'airtable.com',
    'miro.com',
    'typeform.com',
    'surveymonkey.com',
    'wordpress.com',
    'squarespace.com',
    'wix.com',
  ],
  Accounts: [
    'apple.com',
    'icloud.com',
    'google.com',
    'microsoft.com',
    'mozilla.org',
    'proton.me',
    'fastmail.com',
    'yahoo.com',
    '1password.com',
    'lastpass.com',
    'bitwarden.com',
    'dashlane.com',
    'okta.com',
  ],
}

/** Flat lookup: root domain -> generic category name. */
export const DOMAIN_CATALOG: ReadonlyMap<string, string> = new Map(
  Object.entries(CATALOG_DOMAINS_BY_CATEGORY).flatMap(([category, domains]) =>
    domains.map((domain): readonly [string, string] => [domain, category]),
  ),
)
