export { createMcpHttpClient, MCP_PROTOCOL_VERSION } from './http-client.js'
export type { McpHttpClient, McpHttpClientOptions } from './http-client.js'
export { buildSearchString } from './query.js'
export { createMcpMailProvider } from './provider.js'
export type { McpMailProvider } from './provider.js'
